# Generated by Django 5.0 on 2024-01-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_remove_issue_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
