# Generated by Django 5.0 on 2024-01-18 12:47

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, max_length=1000, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='icons/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('buttonMessage', models.CharField(max_length=15)),
            ],
        ),
    ]
