# Generated by Django 5.0 on 2024-01-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_buttonmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='buttonMessage',
            field=models.CharField(max_length=50),
        ),
    ]
