# Generated by Django 5.0 on 2024-01-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default='https://github.com/kishanpadhi291/Atelier_FrontEnd', max_length=1000),
            preserve_default=False,
        ),
    ]
