# Generated by Django 5.0 on 2024-02-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_github'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaredProjects',
        ),
    ]
